### ISSUE TITLE
Handling legacy pages

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/docs#13]
Working on #11 got me thinking about how we should process legacy pages (such as migrating to Ubuntu 10.04, which is definatelly not needed). There are couple of options.

1. Keep the `.md` files in `legacy` and generate the pages
2. Keep the `.md` files in `legacy` but not generate pages for them
3. Remove stale pages and corresponding links. Their existence is still tracked in git.

I would personally vote for `2` as it avoids spam on the page yet still keeps the pages for reference.

**Comment by butlerx** [comment]
id prefer them to be kept in legacy and linked for the time being
once all services have been updated or replaced i think the legacy section could be re visited

**Comment by VoyTechnology** [comment]
So you mean `1`?

**Comment by VoyTechnology** [comment]
Certain pages such as mentioned 10.04 migration really don't need to be generated.

**Comment by butlerx** [comment]
all legacy pages have been moved to legacy in #19 
and as discussed in #24 on a per page basis if a legacy page is determined to have no future value it will be deleted by a pull request
