### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by butlerx** [redbrick/docs#44]
- site/index.html
  *  internally linking to ./apache24, which does not exist (line 1250)
     <a href="./apache24">Web Server</a>
  *  internally linking to ./bind9, which does not exist (line 1241)
     <a href="./bind9">DNS</a>
  *  internally linking to ./dracaccess, which does not exist (line 1262)
     <a href="./dracaccess">DRAC Access</a>
  *  internally linking to ./gpgkeys, which does not exist (line 1267)
     <a href="./gpgkeys">Rootholder public keys</a>
  *  internally linking to ./machines/severus, which does not exist (line 1226)
     <a href="./machines/severus">Severus (backup server) general setup info</a>
  *  internally linking to ./network/hadron, which does not exist (line 1273)
     <a href="./network/hadron">hadron</a>
  *  internally linking to ./network/higgs, which does not exist (line 1275)
     <a href="./network/higgs">Higgs</a>
  *  internally linking to ./network/junos, which does not exist (line 1213)
     <a href="./network/junos">JunOS Configuration</a>
  *  internally linking to ./network/junos, which does not exist (line 1274)
     <a href="./network/junos">JunOS</a>
  *  internally linking to ./procedures/newboard, which does not exist (line 1196)
     <a href="./procedures/newboard">Setting up a new board</a>
  *  internally linking to ./pwsafe, which does not exist (line 1256)
     <a href="./pwsafe">Password Safe</a>
  *  internally linking to ./pyg, which does not exist (line 1263)
     <a href="./pyg">Pygmalion</a>
  *  internally linking to ./services/Mailman, which does not exist (line 1191)
     <a href="./services/Mailman">Mailing Lists (Mailman)</a>
  *  internally linking to ./services/webchat, which does not exist (line 1220)
     <a href="./services/webchat">Webchat (qwebirc)</a>
  *  internally linking to ./todo, which does not exist (line 1158)
     <a href="./todo">Current TODO list</a>
  *  internally linking to ./useradm, which does not exist (line 1240)
     <a href="./useradm">User Management</a>
- site/legacy/machines/sprout/index.html
  *  internally linking to ../OSSEC, which does not exist (line 1192)
     <a href="../OSSEC">OSSEC</a>
- site/legacy/procedures/apacheonmurphy/index.html
  *  internally linking to ../pubcookie, which does not exist (line 1169)
     <a href="../pubcookie">works</a>
- site/legacy/procedures/dirvish/index.html
  *  internally linking to ../../../legacy/procedures/redbrick-apt, which does not exist (line 1249)
     <a href="../../../legacy/procedures/redbrick-apt">redbrick-backup-server</a>
  *  internally linking to ../mysql, which does not exist (line 1815)
     <a href="../mysql">mysql</a>
  *  internally linking to ../redbrick-apt, which does not exist (line 1236)
     <a href="../redbrick-apt">package instructions</a>
  *  internally linking to ../redbrick-apt, which does not exist (line 1302)
     <a href="../redbrick-apt">redbrick-dirvish package</a>
- site/legacy/procedures/murphymysqlclientbug/index.html
  *  internally linking to ../https///bugs.launchpad.net/ubuntu/+source/mysql-dfsg-5.0/+bug/179905, which does not exist (line 1147)
     <a href="../https///bugs.launchpad.net/ubuntu/+source/mysql-dfsg-5.0/+bug/179905">https://bugs.launchpad.net/ubuntu/+source/mysql-dfsg-5.0/+bug/179905</a>
- site/legacy/procedures/new_admin_to_do/index.html
  *  internally linking to ../../../procedures/project-ideas, which does not exist (line 1214)
     <a href="../../../procedures/project-ideas">project-ideas</a>
- site/legacy/procedures/to_do_1502/index.html
- site/legacy/procedures/to_do_1502/index.html
  *  internally linking to ../../../procedures/paphos_migration, which does not exist (line 1149)
     <a href="../../../procedures/paphos_migration">Paphos to do list</a>
- site/legacy/procedures/tomcat-murphy/index.html
  *  internally linking to ../rspm, which does not exist (line 1143)
     <a href="../rspm">rspm</a>
- site/legacy/services/git/index.html
  *  internally linking to ../https///github.com/sitaramc/gitolite, which does not exist (line 1240)
     <a href="../https///github.com/sitaramc/gitolite">gitolite github page</a>
- site/legacy/services/peepd/index.html
  *  internally linking to ../../../legacy/machines/morpheus, which does not exist (line 1146)
     <a href="../../../legacy/machines/morpheus">morpheus</a>
  *  internally linking to ../../../legacy/procedures/redbrick-apt, which does not exist (line 1162)
     <a href="../../../legacy/procedures/redbrick-apt">peepd package</a>
  *  internally linking to ../https///bugs.launchpad.net/hardy-backports/+bug/403791, which does not exist (line 1187)
     <a href="../https///bugs.launchpad.net/hardy-backports/+bug/403791">requested a backport</a>
- site/legacy/services/rbvm/index.html
  *  internally linking to ../redbrick-apt, which does not exist (line 1172)
     <a href="../redbrick-apt">Redbrick apt</a>
- site/machines/the_pdus/index.html
  *  internally linking to ../https///localhost, which does not exist (line 1153)
     <a href="../https///localhost">https://localhost</a>
- site/procedures/backport-packages/index.html
  *  internally linking to ../../legacy/procedures/redbrick-apt, which does not exist (line 1153)
     <a href="../../legacy/procedures/redbrick-apt">apt repo</a>
- site/procedures/newinstalls/index.html
  *  internally linking to ../dirvish, which does not exist (line 1275)
     <a href="../dirvish">dirvish</a>
- site/procedures/redbrick-apt/index.html
  *  internally linking to ../../services/peepd, which does not exist (line 1288)
     <a href="../../services/peepd">peepd-irssi</a>
  *  internally linking to ../../services/peepd, which does not exist (line 1312)
     <a href="../../services/peepd">peepd</a>
  *  internally linking to ../dirvish, which does not exist (line 1325)
     <a href="../dirvish">backup systems</a>
  *  internally linking to ../severus, which does not exist (line 1325)
     <a href="../severus">severus</a>
  *  internally linking to ../thunder, which does not exist (line 1325)
     <a href="../thunder">thunder</a>
- site/procedures/ssl/index.html
  *  internally linking to ../https///ssltools.websecurity.symantec.com/checker/views/certCheck.jsp, which does not exist (line 1199)
     <a href="../https///ssltools.websecurity.symantec.com/checker/views/certCheck.jsp">https://ssltools.websecurity.symantec.com/checker/views/certCheck.jsp</a>
- site/project-ideas/index.html
  *  internally linking to ../lil_cain@redbrick.dcu.ie, which does not exist (line 1159)
     <a href="../lil_cain@redbrick.dcu.ie">Cian</a>
  *  internally linking to ../newinstalls, which does not exist (line 1228)
     <a href="../newinstalls">New Installs Page</a>
  *  internally linking to ../werdz@redbrick.dcu.ie, which does not exist (line 1158)
     <a href="../werdz@redbrick.dcu.ie">Andrew Martin</a>
- site/services/exim/index.html
  *  internally linking to ../../legacy/procedures/redbrick-apt, which does not exist (line 1162)
     <a href="../../legacy/procedures/redbrick-apt">mail2nntp</a>
- site/services/hey/index.html
  *  internally linking to ../redbrick-apt, which does not exist (line 1144)
     <a href="../redbrick-apt">redbrick-apt</a>
  *  internally linking to ../redbrick-apt, which does not exist (line 1147)
     <a href="../redbrick-apt">redbrick-apt</a>
- site/services/icecast2/index.html
  *  internally linking to ../paphos, which does not exist (line 1136)
     <a href="../paphos">paphos</a>
- site/services/ldap/index.html
  *  internally linking to ../ldapsetup, which does not exist (line 1323)
     <a href="../ldapsetup">ldapsetup</a>
- site/services/mysql/index.html
  *  internally linking to ../dirvish, which does not exist (line 1160)
     <a href="../dirvish">backed</a>
- site/services/nfs/index.html
  *  internally linking to ../../machines/azazel, which does not exist (line 1138)
     <a href="../../machines/azazel">Azazel</a>
  *  internally linking to ../dirvish, which does not exist (line 1140)
     <a href="../dirvish">dirvish</a>
  *  internally linking to ../thunder, which does not exist (line 1140)
     <a href="../thunder">Thunder</a>

**Comment by VoyTechnology** [comment]
Some of the pages don't exist any more. I think we should disable the link check for now until we have the links fixed, so we don't block other builds
