### ISSUE TITLE
Make mkdocs.yml more generic

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/docs#5]
By the looks of it, everything page in `mkdocs.yml` has to be manually added. Is there a way to automatically add new pages to the config?

**Comment by butlerx** [comment]
this sounds good to me. if i remeber the mkdocs.yml is mainly what appears on the menu

**Comment by VoyTechnology** [comment]
Yea, just checked. It does get generated automatically. The pages section just gives you ability to create a menu and submenu. Closing as its WAI.
