### ISSUE TITLE
Documentation Subsections

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/docs#6]
Every page now is in the root of the docs directory. I propose we migrate them into following subsections:
* __legacy__: Very out of date, but still somewhat useful as a data archive. It will contain other subsections.
* __web__: Web related documentation, such as Apache, suPHP etc.
* __servers__: Server information
* __services__: The services that redbrick runs.
* __network__: Networking gear and network configuration

To make this work probaby a change is needed with #5.

This issue will be updated as more sections are needed.

**Comment by VoyTechnology** [comment]
In fact... it looks like it would be easier to move everything to `legacy` first, and then write new documentation based on it..

**Comment by butlerx** [comment]
these sections make sense but we might also have to separate some of the legacy files as some have info that should go in to say web despite being on the mutphy documentation

**Comment by butlerx** [comment]
not everything is legacy just easily 80-90%

**Comment by butlerx** [comment]
but id like #5 to be looked at before this as is defines what we can do with the files

**Comment by butlerx** [comment]
closed in #19
